FROM python:3.13-slim

ARG DAGSTER_VERSION=1.12.20
ARG DAGSTER_LIBS_VERSION=0.28.20

RUN pip install --no-cache-dir \
    dagster==${DAGSTER_VERSION} \
    dagster-graphql==${DAGSTER_VERSION} \
    dagster-webserver==${DAGSTER_VERSION} \
    dagster-postgres==${DAGSTER_LIBS_VERSION} \
    dagster-docker==${DAGSTER_LIBS_VERSION}

ENV DAGSTER_HOME=/opt/dagster/dagster_home/

RUN mkdir -p $DAGSTER_HOME

COPY docker/dagster.yaml docker/workspace.yaml $DAGSTER_HOME/

WORKDIR $DAGSTER_HOME
